name=Lumen_Forph
version=1.1.0
author=Saul Fernandes
maintainer=Saul Fernandes <saul-jazz@hotmail.com>
sentence=Protocolo de comunicação serial para interfaces IHM industriais.
paragraph=Biblioteca customizada da Forph Equipamentos para empacotamento de dados via serial.
category=Communication
url=https://github.com/saulfernandes/Lumen_Forph
architectures=*
includes=LumenProtocol.h